image: docker:19.03.1

variables:
    DOCKER_IMAGE: 448051883053.dkr.ecr.us-east-1.amazonaws.com/cloudgeeks-app
    TAG: latest
    DOCKERFILE_LOCATION: ./
    DOCKER_VERSION: Docker-19.03.6-ce
    DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

stages:
  - build
  - push


###############
#   Builds    #
###############

build-docker-latest:
  stage: build
  script:
    - echo "AWSCLI Installation"
    - apk add --no-cache python3 py3-pip && pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
    - aws --version 
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 448051883053.dkr.ecr.us-east-1.amazonaws.com
    - docker build -t $DOCKER_IMAGE:$TAG $DOCKERFILE_LOCATION
  only:
    - main
   

###############
#   Push    #
###############

push-to-ecr:
  stage: deploy
  environment:
    name: dev
  script:
    - echo "Pushing to ECR"
    - docker push $DOCKER_IMAGE:$TAG
  only:
    - main

