image: docker:19.03.1

variables:
    DOCKER_IMAGE: registry.gitlab.com/quickbooks2018/gitlab-argocd
    DOCKERFILE_LOCATION: ./
    DOCKER_VERSION: Docker-19.03.6-ce
    DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

stages:
  - build


###############
#   Builds    #
###############

build-docker-latest:
  stage: build
  script:
    - apk add curl
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install -i /usr/local/aws -b /usr/local/bin/aws
    - aws --version && docker -v
    - docker login -u argocd -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $DOCKER_IMAGE:latest $DOCKERFILE_LOCATION
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

