image: docker:19.03.1

variables:
    DOCKER_IMAGE: 874828247585.dkr.ecr.us-east-1.amazonaws.com/cloudgeeks-app
    BUCKET: s3://cloudgeek-terraform
    DOCKERFILE_LOCATION: ./
    DOCKER_VERSION: Docker-19.03.6-ce
    DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

stages:
  - build
  - deploy


###############
#   Builds    #
###############

build-docker-latest:
  stage: build
  environment:
    name: dev
  script:
    - echo "AWSCLI Installation"
    - apk add --no-cache python3 py3-pip && pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
    - aws --version 
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 874828247585.dkr.ecr.us-east-1.amazonaws.com
    - echo "latest" > TAG && aws s3 cp TAG $BUCKET/TAG
    - export TAG=$(cat TAG)
    - aws s3 cp repo.sh $BUCKET/repo.sh
    - docker build -t $DOCKER_IMAGE:$TAG $DOCKERFILE_LOCATION
    - docker push $DOCKER_IMAGE:$TAG
  only:
    - main
   

###############
#   Deploy    #
###############

deploy-to-application-repo:
  stage: deploy
  environment:
    name: dev
  script:
    - aws s3 cp .
    - chmod +x repo.sh
    - ./repo.sh
    - echo "Deploy to Kubernetes"
  only:
    - main

